server:
  port: 5000
  ssl:
    certificate: "cert.crt"
    enabled: true
spring:
  datasource:
    url: "jdbc:postgresql://188.72.108.228:5432/postgres"
    username: "root"
    password: "Kunzhut2023!"
  flyway:
    baseline-on-migrate: true
    defaultSchema: public